# HERE is A POD!!!
# Simple Kubernetes Pod to deploy the app contained in nigelpoulton/getting-started-k8s:1.0
# Pod object definition
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: nigelpoulton/getting-started-k8s:1.0
      ports:
        - containerPort: 8080
